keys:
  - &Atlas age18e3wp3a62t9yc8fe2yvjaxxpc4ze984ljead6ljh0av9pc02cp4qpl6ndt
  - &Ingress age1wnxksdjsfc2nflmxxzqnqanwrl0peu23zzt8qhe6rl623de5e5sqwvpm9q

creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
      - age:
          - *Atlas
          - *Ingress
