keys:
  - &Atlas age18e3wp3a62t9yc8fe2yvjaxxpc4ze984ljead6ljh0av9pc02cp4qpl6ndt
  - &Icarus age1s6mpeq7tundjx4xf33dp4alndhjcv5pu6kdr2szgzdy05pw9zyuqugduyw
  - &Hermes age1wnxksdjsfc2nflmxxzqnqanwrl0peu23zzt8qhe6rl623de5e5sqwvpm9q
  - &Olympus age196gkf4kmf87qg4dxmww6pm8xvwk0rm6fp9ugkegufk8uennjkcyqhuzkac
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
      - age:
          - *Atlas
          - *Icarus
          - *Hermes
          - *Olympus

  - path_regex: secrets/services.yaml$
    key_groups:
      - age:
          - *Atlas
          - *Olympus
