proxmox-api-token: ENC[AES256_GCM,data:h/Qv0MFeshc1v6kZIxFZWjoRwXzQX2DyW9w3JqgqS3CXsMSS,iv:Dxkdf7E7dk4ygPwplbIuc5rQt3fys62ulaU35+n7AsA=,tag:iEhYdY5tUZ+nwzKWQteDeA==,type:str]
gitea-token: ENC[AES256_GCM,data:LvcaIeAcfp+dIb00w+KA42AH65Gy0TczEBDZ8bICiymjr2TKbBSo7Q==,iv:3zTisPEM2vBBPbqXNzuMiaSgPbIi4nAbBKTtdzAzHLw=,tag:yG9ks+axgHEcN9KWLZOiuA==,type:str]
nextcloud:
    admin_pass: ENC[AES256_GCM,data:aXk7MfWoTA==,iv:9FI1CdrQGX8jBjrMYMEYNBMxmXbvZ6eHjtVVe/GUYOU=,tag:5f4S25tMzP0ACl4G1q/s5w==,type:str]
authentik:
    secret_key: ENC[AES256_GCM,data:KMRBs9kzmh9ut87ZgKboHgUk0RYbzVh6Lr328eS3JNSZKa0Zq5Fmx/EOECmR/gQ5SN0ElgMqdcfUP/iqbXc3QOt/saY=,iv:r9bHqm335sAnOfLn4K3poG7FmW3p1M1XQZlhZTEVnAU=,tag:BnzLKHmL+oUnxEeHyjxxMw==,type:str]
    db_pass: ENC[AES256_GCM,data:Hbk4/xfDxwDuqMm24LxDLULmgYNZx85yfefrgKBPBmUx60FM76SAOu9lxwiabmzsRmgcKgC5XtC7CvRKKlMTvPpU+xBHxQl+GRXXXBeHAA==,iv:Vpah1skJuj8gxMGTlDOKOkPkOsL8sPCJz+dwk+wXueI=,tag:V9kN5n6zghiCKLFc8NPF8Q==,type:str]
pterodactyl:
    api-key: ENC[AES256_GCM,data:fLT05zY=,iv:jsyRlxbEU0QuqAeQSFYhtzW9Cs4KKu3Y+BvaDN5M0Dc=,tag:09uCaRyZO9hs5s1UpyyM/g==,type:str]
sops:
    age:
        - recipient: age18e3wp3a62t9yc8fe2yvjaxxpc4ze984ljead6ljh0av9pc02cp4qpl6ndt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzdDNDSDRoL0tzKzczcnhw
            dVlJb0dNTDlVdXVCWDdKN3FHazBqMTRUdkRZCmYzV3I1eGo4S1RwTWFibFRYdDdU
            WGhxUUJrMFFFeWZDeWxSVXZNVXhyTzgKLS0tIDUvTHNPTjJkNUh5WDY5cE8vd0xK
            dWhVUmR0SDZBa2dUNFg0MnFUZHNVbVEKmRPaUN7fiut2prLjyDzHZTOyyw7K/0xg
            qF8y+8NKq9cYBZJxzlQM8amcuwKNUYz9cKf+E7rNM39CCr5rtaissw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age16h4rus0c80t5lelf6zy8pvch2ffhpjenzg3cr7wuv92gd5tugveqh6e7fs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMOXlRNU96WjBXKzhDUkdO
            blBhc0phTWptUjlJejcxVm5QNEdQR3E3VlVrClZsL21XSDBZaStjYWJUTW5oYWhZ
            YVd3aXF2S0hxYXErMU9FNDF4N1BrdFEKLS0tIG9SSFU5WHFNdTZRd0FsKzhpVGxo
            enlCOHRMdEp0SEhBOWYwc0pmWnhncFEKhaaoQaY4EAl6FneWNhmXnFK1MPE2gZ0D
            S/rYaXIstwt4GAhMIOU/H/3pf9t4nXSa6UqhgbemSgos2jKY2v3CXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-26T21:55:24Z"
    mac: ENC[AES256_GCM,data:HjFQo4tSode1f/DF23M9GxQm6sEXo0aXFTMDp9KiwJdw8De4KHqeLl+O0XqXyXM7S01CBVFBzjpB2lw0k+4mqTbesA3h3q8bZd+jMK8nvAxX8mrLWN8sH8hPyBwLfxwior1GJIXBtlp0Yvc+1eGzR0a7qhOlO9HquPnEMYZy3RU=,iv:pf7i/j41zIo0jb2RoBN/Ean11VmRJOmIbDq6MzIbggw=,tag:EqBjJRAN5memLqBDSnnVjg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
