nixAccessToken: ENC[AES256_GCM,data:klNX8g/iN2v7WSs8KNn6OpLI4RMP08I9CPkSw+VIYDd+VgQohKGkKUe2Kqr9kTX06kBA8yJ7YBvfrV8TijOWC5xGOSSNsttDOh2sqOfhooeXjajtxkzDNH7GmbCc,iv:eBOqVTvsZunNduTfKCmzKRS2DZR8cSQ/wb3gL9fhlbQ=,tag:PyTS2+j47IwJgYnw1IEnfQ==,type:str]
personal:
    email: ENC[AES256_GCM,data:oo/Gg3jAIQllJcIcaFBdmo6zM3RW,iv:YDC54hjHwwDHi6Cfb6ulxdtKV+kg7JvqYA6Wacfk0Xk=,tag:V9cGJxsENIN0UkEGfqxu/A==,type:str]
cloudflare:
    api_token: ENC[AES256_GCM,data:PXcWv2sUKER+VZOLnxqAoTIPx2O5tmUe9PU0n2RZkSCVEdZFmnbv+fRJeg7ezyi2K8iUTAs=,iv:xGFqG2gHVQkGtSzigdu9x6hTgKOv0TFgdRqQk5LtjXY=,tag:zunA+X51WHPcmHI2W0K2ug==,type:str]
authentik:
    secret_key: ENC[AES256_GCM,data:KMRBs9kzmh9ut87ZgKboHgUk0RYbzVh6Lr328eS3JNSZKa0Zq5Fmx/EOECmR/gQ5SN0ElgMqdcfUP/iqbXc3QOt/saY=,iv:r9bHqm335sAnOfLn4K3poG7FmW3p1M1XQZlhZTEVnAU=,tag:BnzLKHmL+oUnxEeHyjxxMw==,type:str]
    db_pass: ENC[AES256_GCM,data:Hbk4/xfDxwDuqMm24LxDLULmgYNZx85yfefrgKBPBmUx60FM76SAOu9lxwiabmzsRmgcKgC5XtC7CvRKKlMTvPpU+xBHxQl+GRXXXBeHAA==,iv:Vpah1skJuj8gxMGTlDOKOkPkOsL8sPCJz+dwk+wXueI=,tag:V9kN5n6zghiCKLFc8NPF8Q==,type:str]
speedtest:
    app_key: ENC[AES256_GCM,data:NpJ0oWRqp0CHiQWOUgDIWxcQDS/jsncvvBrjNkf/rrBWpd5ULppcSNU2UqJYHN6n/Ywa,iv:/vVZbWrNXvkhyjcYpFdnuTWzyMeqO7bsF+WG6TspymE=,tag:YY7pggswltKdq4WUil1jag==,type:str]
kavita:
    token_key: ENC[AES256_GCM,data:StZw0xbu7YeJqMfYWkOCVQ2bnmXLppBhkEGiytnmEwVa6O/RAh1NBAWV4lLyh8zSgVMDDjGc0ZSXuD8ZxrT/h2rt7sZcMurvG9qkmmQZpygmdJpqWrcAPg==,iv:ZztGl8Kxxi60DSamWIgUaq7VKh0nxb/iU605Z2R08bE=,tag:g6H/tmKiP8klEB+WccoIhA==,type:str]
lldap:
    jwt_secret: ENC[AES256_GCM,data:Uzxlwwt0zDDQ95hTFXzOrWyjRa4=,iv:oiB1C8Q3C3GZdnQNGqIAwog6mDV9tztxShNxPWMZ3Is=,tag:AzGP2TepAS40VeGPIohMzg==,type:str]
    admin_pass: ENC[AES256_GCM,data:eExE67AKWYI=,iv:BmM2Rsz/zH/maszFDqCDf2G6+3w+QzEeOFZ4uwz3Ntc=,tag:F/EnXloEK2cfe6ePuWl/EA==,type:str]
sops:
    age:
        - recipient: age18e3wp3a62t9yc8fe2yvjaxxpc4ze984ljead6ljh0av9pc02cp4qpl6ndt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhMzdPQXN0Q0Z0dHpuNGFj
            c3ppMkNCa09KaWhkcHBZb0NMR200QWgyY1ZNCnVDWTc4cVFVc2oyUDdYdmFZd0NG
            dWFYa2UyVGNmZGVpekg1MlBBVFl4Q00KLS0tIDFxSGJUTVdpaU1vVnB0Uk9jL1VG
            bTZLRWFSWE96ZmEzTThtaUs3ZE4vbFEKEVn73Ox7VKnK29CrsloHp0fv46VtcCAN
            uRauAW3bsSvWPVoDLCGT1D/AU7k+TPEsGrXSondwyfV9RSu+hMv92A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age196gkf4kmf87qg4dxmww6pm8xvwk0rm6fp9ugkegufk8uennjkcyqhuzkac
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqSWluc2ZaMkZudTJ6dUkv
            S3dmV0ZTcEZ4MkNSVksySjhqTUgzNituTFRNCkJiUWRKVkRxUGxQR3o2Y3hqMWxE
            QkN1RzdVbnQ4UkpTZ24zMFVTcEFaTVEKLS0tIFFWa3kvODR3NVR4VHBWZ2Z3dElV
            QzZkWTJ1K3p4UnlwYm1CNHJ1SmhxVVEKykzKLbSBmkFL9YBG19RZqe+8IZF7jFKd
            Ivmezpe3U4jooAVql4+QBJzoynl6jI5oOM9dv2wLYUn8cuO7bSvjsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-22T20:50:37Z"
    mac: ENC[AES256_GCM,data:HM3r2XSN2tHWqhd28nsAvxNiGKAaa72O3ZFVSsvj51EPsoQXtopj2xn5UHSXCiM4m9pjTNQfufkkyFZnhp5e4xU1dvNsFo2dzY44NWhRgHB/yjRtR8lKIQYF1Zu0bTRiKbJQHmh9hNJ5gc1q0AzNHnRzUgnFDhvnTpRG2Mj+J6s=,iv:vRtBr+EF4msOOoATUBbR/3kHgOeNwr/9R9s90h1RplA=,tag:uMzN8WJP4tq7VCDLwwUlCg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
